# This is a basic workflow to help you get started with Actions

name: build-github-pages-and-transfer-to-dev-repo
on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@dev
    - name: Deploy to GitHub Pages - Python
      uses: JacksonMaxfield/github-pages-deploy-action-python@2.1.0
      env:
        ACCESS_TOKEN: ${{ secrets.fpcbksecret }}
        REPOSITORY_NAME: FAIRplus/cookbook-dev
        BASE_BRANCH: master # The branch the action should deploy from.
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: docs # The folder the action should deploy.
        BUILD_SCRIPT: pip install jupyter-book && jupyter-book build docs --overwrite  
