name: transfer-dev-to-external-repo
on:
  push:
    branches:
      - dev

jobs:
  copy-to-other-repo:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout dev branch
      uses: actions/checkout@v2
      with:
        ref: dev ## checkouts "dev" branch
    - name: Push to other repo
      uses: pixta-dev/repository-mirroring-action@v1
      with:
        target_repo_url:
          git@gitlab.com:FAIRplus/cookbook-dev.git
        ssh_private_key:                                # <-- use 'secrets' to pass credential information.
          ${{ secrets.ACTIONS_DEPLOY_KEY }}
