name: build-from-main-branch-and-deploy-to-external-repo
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-deploy-to-other-repo:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout dev branch 🛎️
      uses: actions/checkout@v2 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
      with:
        persist-credentials: false
        ref: main
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Record Python version
      run: python -V
    - name: Install jupyter-book==0.10.2 and fixed dependencies
      run: pip install -r requirements.txt
    - name: Record used pip packages
      run: pip freeze 
    - name: Install mermaid and build the book
      run: ./scripts/build.sh
    - name: Check for important warnings
      run: ./scripts/extract-warnings.sh 
    - name: Install SSH Client 🔑
      uses: webfactory/ssh-agent@v0.4.1
      with:
        # ssh-private-key: ${{ secrets.ACTIONS_DEPLOY_KEY }}   ## for push into cookbook-dev
        ssh-private-key: ${{ secrets.DEPLOY_GHPAGES_INTO_MAIN_REPO }}  ## for push into the-fair-cookbook
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        SSH: true
        BASE_BRANCH: main #The branch of this repository which should be transfered from.
        REPOSITORY_NAME: FAIRplus/the-fair-cookbook # The repository on github.com to which will be deployed = pushed.
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: _build/html # The folder the action should deploy.
        
